name: Comment Sonar

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run comment-sonar
        uses: rn404/comment-sonar@0ed24ba2c62c6a3016b92133cae129e39b6d07bb
