name: Comment Sonar

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run comment-sonar
        uses: rn404/comment-sonar@a3f7422d64d66e237b1c930946a5fab9e825da9b
