name: Comment Sonar

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run comment-sonar
        uses: rn404/comment-sonar@7d3355c2363b0e1ce91d755039e739e02ffe6da0
